@startwbs
*[#LightGreen] CEO : Tomasz K. Stanczac
**[#LightGreen] CTO : Greg Vardy
*** PM : Borys Tam
****[#SkyBlue] Atlantis
****-[#SkyBlue] Julius Yls
****-[#SkyBlue] Anastasia Zaitceva
*****[#SkyBlue] Yohenba Kshetrimayum
*****[#SkyBlue] Parth Padawarth 
*****[#SkyBlue] Ayman Bouchareb 
***-[#pink] Other Teams
**-[#pink] Other Projects
@endwbs