@startuml
User -> Browser: Visits website
Browser -> User : Prompt login
alt "Web2 login"
   User    --> Browser : Enter creadentials
   Browser --> Browser : Verify input
   Browser --> Server  : Send over http 
   Server  --> Server  : Authenticate credentials
   Server  --> Browser : Send response
   alt "User registered?"
      Browser --> User    : Show Main Menu
   else 
      Browser --> User    : Show Error
   end
else "web3 login"
   User    --> Browser : Scan QR-Code 
   Browser --> Browser : Extracts walletId
   Browser --> Blockchain : Query Tokens
   Blockchain --> Browser : Check Tokens
   alt "Registration Token Found?"
      Browser --> User    : Show Main Menu
   else 
      Browser --> User    : Show Error
   end
end
@enduml