CREATE OR REPLACE TABLE Petition (
    IDP INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Titre VARCHAR(32) NOT NULL,
    Description TEXT NOT NULL,
    DatePublic date NOT NULL
) ENGINE = InnoDB;

CREATE OR REPLACE TABLE Signature (
    IDS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    IDP INT NOT NULL,
    IDU INT NOT NULL,
    DateS DATE NOT NULL,
    CONSTRAINT `id_petition`
        FOREIGN KEY (IDP)
        REFERENCES Petition (IDP)
    CONSTRAINT `id_user`
        FOREIGN KEY (IDU)
        REFERENCES User (IDU)
) ENGINE = InnoDB;

CREATE OR REPLACE TABLE User (
    IDU INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    Age Int NOT NULL,
    Gender Boolean NOT NULL,
    Password VARCHAR(20) NOT NULL,
    Email VARCHAR(64) NOT NULL,
    Country VARCHAR(50) NOT NULL,
) ENGINE = InnoDB;